'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type SealRouletteArc, type SealRouletteCustomEvent } from "@sealambda/components";
import { MyComponent as MyComponentElement, defineCustomElement as defineMyComponent } from "@sealambda/components/dist/components/my-component.js";
import { SealRoulette as SealRouletteElement, defineCustomElement as defineSealRoulette } from "@sealambda/components/dist/components/seal-roulette.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type MyComponentEvents = NonNullable<unknown>;

export const MyComponent: StencilReactComponent<MyComponentElement, MyComponentEvents> = /*@__PURE__*/ createComponent<MyComponentElement, MyComponentEvents>({
    tagName: 'my-component',
    elementClass: MyComponentElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as MyComponentEvents,
    defineCustomElement: defineMyComponent
});

type SealRouletteEvents = {
    onSpinning: EventName<CustomEvent<void>>,
    onStopped: EventName<SealRouletteCustomEvent<[number, SealRouletteArc]>>
};

export const SealRoulette: StencilReactComponent<SealRouletteElement, SealRouletteEvents> = /*@__PURE__*/ createComponent<SealRouletteElement, SealRouletteEvents>({
    tagName: 'seal-roulette',
    elementClass: SealRouletteElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onSpinning: 'spinning',
        onStopped: 'stopped'
    } as SealRouletteEvents,
    defineCustomElement: defineSealRoulette
});
